apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: market-redis-monitor
  namespace: market-service
  labels:
    app: market-redis
    release: prometheus
spec:
  selector:
    matchLabels:
      component: redis-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
