apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qdrant-monitor
  namespace: ai-service
  labels:
    app: ai-qdrant
    release: prometheus
spec:
  selector:
    matchLabels:
      component: qdrant-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
